In [24]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.naive_bayes import GaussianNB,BernoulliNB,MultinomialNB
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.datasets import load_iris

import warnings
warnings.filterwarnings('ignore')

In [25]:
# load the dataset
df = load_iris()
X = df.data
y = df.target

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [27]:
gnb=GaussianNB()
gnb.fit(X_train,y_train)
y_pred=gnb.predict(X_test)
print('accuracy_score : ',accuracy_score(y_test,y_pred))
print('confusion_matrix : ',confusion_matrix(y_test,y_pred))
print('classification_report : ',classification_report(y_test,y_pred))

accuracy_score :  0.9777777777777777
confusion_matrix :  [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
classification_report :                precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45



In [28]:
mnb=MultinomialNB()
mnb.fit(X_train,y_train)
y_pred=mnb.predict(X_test)
print('accuracy_score : ',accuracy_score(y_test,y_pred))
print('confusion_matrix : ',confusion_matrix(y_test,y_pred))
print('classification_report : ',classification_report(y_test,y_pred))

accuracy_score :  0.9555555555555556
confusion_matrix :  [[19  0  0]
 [ 0 12  1]
 [ 0  1 12]]
classification_report :                precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.92      0.92      0.92        13
           2       0.92      0.92      0.92        13

    accuracy                           0.96        45
   macro avg       0.95      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45



In [29]:
bnb=BernoulliNB()
bnb.fit(X_train,y_train)
y_pred=bnb.predict(X_test)
print('accuracy_score : ',accuracy_score(y_test,y_pred))
print('confusion_matrix : ',confusion_matrix(y_test,y_pred))
print('classification_report : ',classification_report(y_test,y_pred))

accuracy_score :  0.28888888888888886
confusion_matrix :  [[ 0 19  0]
 [ 0 13  0]
 [ 0 13  0]]
classification_report :                precision    recall  f1-score   support

           0       0.00      0.00      0.00        19
           1       0.29      1.00      0.45        13
           2       0.00      0.00      0.00        13

    accuracy                           0.29        45
   macro avg       0.10      0.33      0.15        45
weighted avg       0.08      0.29      0.13        45

